name: flutter_video_app
description: Demo Flutter app with login, user list (ReqRes), and one-to-one video via Agora.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.3.3
  dio: ^5.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  permission_handler: ^11.4.0
  agora_rtc_engine: ^6.5.3
  shared_preferences: ^2.1.5
  uuid: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
